### ISSUE TITLE
rebuild ok but start not

### ISSUE THREAD

**Issue by adelmrk** [AntonBaluev/PressureTransientAnalysis#5]
Hello Dear Anton ,

After change Startup type project , I have rebuild fine

![rebuild](https://user-images.githubusercontent.com/5977920/33794225-e24454fa-dcdc-11e7-90da-d3a2a8e3778a.jpg)

but , when I do Start button there is a problem

![start](https://user-images.githubusercontent.com/5977920/33794263-8a1476d8-dcdd-11e7-84f6-db8a51225a3c.jpg)

I done googling and test some trick but not run as a project
So, how to run like a project not library ?

Thanks .

**Comment by AntonBaluev** [comment]
In F# project, there is a .fsx file. Open it, select all content, right click and select menu "Execute in Interactive".

**Comment by adelmrk** [comment]
I`ve Execute it now and see two beauty charts .
So, if I want to export setup file to install this software, how can I do this ?

**Comment by AntonBaluev** [comment]
I don't think it is possible, it is a just a library.
